name: KinD tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: governance-policy-addon-controller

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.18'
        # KinD tags: https://hub.docker.com/r/kindest/node/tags
        # (OCP 4.6 runs Kubernetes v1.19)
        kind:
          - 'v1.19.16'
          - 'latest'
    name: KinD tests
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
      with:
        path: governance-policy-addon-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Go - ${{ matrix.go }}
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: ${{ matrix.go }}

    - name: Verify modules
      run: |
        go mod verify

    - name: Verify format
      run: |
        make fmt
        git diff --exit-code
        make lint

    - name: Unit and Integration Tests
      run: |
        make test

    - name: Create KinD Cluster (${{ matrix.kind }}) and deploy components
      env:
        KIND_VERSION: ${{ matrix.kind }}
      run: |
        ./build/manage-clusters.sh
        make wait-for-work-agent

    - name: E2E Tests
      run: |
        export GOPATH=$(go env GOPATH)
        make e2e-test-coverage

    - name: Test Coverage Verification
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        make test-coverage
        make coverage-verify

    - name: Test Coverage and Report Generation
      if: ${{ github.event_name == 'push' }}
      run: |
        make test-coverage | tee report_unit.json
        make gosec-scan
        cat gosec.json

    - name: SonarCloud Analysis
      if: |
        github.event_name == 'push' && 
        github.repository_owner == 'stolostron'  &&
        matrix.kind == 'latest'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: config-policy-controller
        args: >
          --debug

    - name: Debug
      if: ${{ failure() }}
      run: |
        RUN_MODE="debug" ./build/manage-clusters.sh

    - name: Clean up cluster
      if: ${{ always() }}
      run: |
        RUN_MODE="delete" ./build/manage-clusters.sh
